version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ${ENV_FILE:-.env}
    environment:
      - ENV_FILE=${ENV_FILE:-.env}
    volumes:
      - ./backend:/app
    networks:
      - docgenius-network
    # For production, remove volumes and add:
    # command: ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "app.main:app", "--bind", "0.0.0.0:8000"]

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    env_file:
      - ${ENV_FILE:-.env}
    environment:
      - VITE_API_URL=http://localhost:8000/api  # Use localhost for browser access
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - docgenius-network
    depends_on:
      - backend

  # Add database if needed
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-docgenius}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - docgenius-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  
networks:
  docgenius-network:
    driver: bridge